verify

diff --git a/.github/workflows/infracost.yml b/.github/workflows/infracost.yml
--- a/.github/workflows/infracost.yml
+++ b/.github/workflows/infracost.yml
@@ -29,6 +29,14 @@ jobs:
         uses: infracost/actions/setup@v3
         with:
           api-key: ${{ secrets.INFRACOST_API_KEY }}
+      - name: Check secret exists
+        run: |
+          if [ -z "${{ secrets.INFRACOST_API_KEY }}" ]; then
+            echo "Secret missing"
+            exit 1
+          else
+            echo "Secret found"
+          fi
 
       - name: Infracost Diff
         uses: infracost/actions/diff@v4
